name: Local Testing Workflow (Writeable)

on:
  push:
    branches: 
      - dev/workflow-testing
      - dev/action-testing

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Read the test issue json
        shell: pwsh
        id: loader
        run: |
          $issue = Get-Content ".github/workflows/test-data/test-issue.json"
          $issue = $issue | Join-String -Separator " "
          "GITHUB_ISSUE=$issue" >> $env:GITHUB_OUTPUT
      - uses: mattleibow/labeled-by-ai@dev/action-testing
        with:
          # labels: |
          #   area/action
          #   area/ai
          #   area/function
          # label-pattern: '^area/.*'
          label-config: .github/labeler-rules.json
          issue-json: ${{ steps.loader.outputs.GITHUB_ISSUE }} # testing pipeline only
